### ISSUE TITLE
Page breaks at tweaked search

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#1]
https://ocr.yiddishbookcenter.org/?page=1&query=%2B%D7%90%D6%B7%D7%A8%D7%95%D7%99%D7%A1%D7%93%D7%A8%D7%B2%D7%A2%D7%9F+%2B%D7%A4%D6%BF%D7%9C%D7%90%D6%B7%D7%9D+%7E10&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score

This was the search I tried: 
+אַרויסדרײען +פֿלאַם ~10

(In transcription this would be:) +aroysdreyen +flam ~10
it is connected to the ~10

I am altogether not sure about the right solution for this problem. It shows, that it is not intuitive when to use + and when to use "".
When the definitive version is online, an error page could link to the user-guide and say something like: 'probably you made an illegal search, check again the legal options.'

**Comment by urieli** [comment]
The ~ operator only works directly after a [quoted expression](https://ocr.yiddishbookcenter.org/?page=1&query=%22%D7%90%D6%B7%D7%A8%D7%95%D7%99%D7%A1%D7%93%D7%A8%D7%B2%D7%A2%D7%9F+%D7%A4%D6%BF%D7%9C%D7%90%D6%B7%D7%9D%22%7E10&author=&author=&authorInclude=true&title=&fromYear=&toYear=&sortBy=score) and serves to allow up to _n_ words between the words in the expression.

However, as you indicate, the error shouldn't show an ugly crash screen, and should instead point the user at online help! I'll have to figure out why the error above behaves differently than, say, [this one](https://ocr.yiddishbookcenter.org/?page=1&query=%22%D7%90%D6%B7%D7%A8%D7%95%D7%99%D7%A1%D7%93%D7%A8%D7%B2%D7%A2%D7%9F+%D7%A4%D6%BF%D7%9C%D7%90%D6%B7%D7%9D&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score).

**Comment by urieli** [comment]
Fixed in 98c7981ad0c6866748b80c35b2340cdc011b5e7f

Apparently [without the quotes](https://ocr.yiddishbookcenter.org/?page=1&query=%D7%90%D6%B7%D7%A8%D7%95%D7%99%D7%A1%D7%93%D7%A8%D7%B2%D7%A2%D7%9F%7E2&author=&author=%7C&authorInclude=true&title=&fromYear=&toYear=&sortBy=score), this is constructing a "[fuzzy search](https://lucene.apache.org/solr/guide/7_5/the-standard-query-parser.html#fuzzy-searches)".
The Jochre highlighter didn't know how to handle this type of search.
