### ISSUE TITLE
Mistakes in Book Center's titles need to be corrected / correctable

### ISSUE THREAD

**Issue by mirjam-amsterdam** [urieli/jochre#4]
As we all know, the titles and names of the scanned books of the Yiddish Book Center contain endless numbers of mistakes. Now, with Jochre, they become even more exposed and should be corrected or correctable. Could you try convincing them to do something about them?
![screenshot_20181104-2](https://user-images.githubusercontent.com/44893880/48516571-fbe07e00-e863-11e8-8d5f-cf477b7e0a5e.png)

**Comment by mirjam-amsterdam** [comment]
another example
![screenshot_20181104-5](https://user-images.githubusercontent.com/44893880/48517314-321efd00-e866-11e8-96ee-ef72d05845fb.png)

**Comment by urieli** [comment]
I'll contact them, and see about adding this functionality.
Note however: Jochre currently uses metadata from the Internet Archive. I've been told that there's an internal database with higher quality metadata, so that might give us a cleaner starting point.

**Comment by mirjam-amsterdam** [comment]
I do hope they are planning on uploading their better metadata to archive.org!
Thanks,
Mirjam

**Comment by aclooney** [comment]
Hi Mirjam, 

We just saw your comments here. We'll take a look at the issues above, and thanks for submitting them. As you know, we have over 12,000 books that were cataloged at different times, so errors do show up. We do correct them when they are reported. 

Our internal database of metadata uses standard MARC library cataloging, which is what the metadata you find on Internet Archive draws from. The data in our MARC cataloging records is more robust and detailed than what you find on Internet Archive, but if there is an error in the Internet Archive metadata, that's usually because there is an error in the cataloging record. If an error is reported, we correct it in the Internet Archive metadata and in the original MARC record. 

In any case, we very much appreciate it when errors are reported. Until we have a mechanism for reporting metadata errors within JOCHRE, you can email us at digitalcollections@yiddishbookcenter.org. 

Thanks, 

Amber Kanner Clooney
Web Developer and Digital Projects Librarian
Yiddish Book Center

**Comment by mirjam-amsterdam** [comment]
Hi Amber,
That sounds like opening Pandora's box...
Elissa once pointed me to https://fcaw.library.umass.edu and there I will
be able to see the MARC records.
Thansk & Best,
Mirjan


Mirjam Gutschow
Mariotteplein 15
1098 NW Amsterdam
Nederland
+31-20-3202086

**Comment by aclooney** [comment]
Hi Mirjam, 

Yes, you can see the MARC records there. If you find errors in the MARC records, please let us know! We will be happy to correct them. 

Thanks, 

Amber

**Comment by urieli** [comment]
I've upgraded the Yiddish Book Center server to version 2.3.0.
It's now possible to correct book metadata.

**Comment by mirjam-amsterdam** [comment]
great!
How will correcting the metadata of the Book Centers titles / authors /
publishing houses work?
Will the users need explanation? Will the Book Centre get notofied?
(Eg: Through comparison with their catalogue in "
https://fcaw.library.umass.edu/" I noticed that sometimes what seems to be
a mistake with main title and subtitle is within the system.)
Best,
Mirjam

**Comment by urieli** [comment]
Hi Mirjam,

The book center is automatically notified by e-mail of any corrections made - this is setup in Jochre's configuration files.
They have an internal process for reviewing the change and propagating it to their catalogue.
They can also "undo" the correction (which is currently automatically applied to the Jochre index).

Hopefully the interface is self-explanatory, and no explanation is required - we'll see!

You mention subtitle, which is a good point: currently, Jochre does not store a subtitle field, but this seems wrong to me. I need to check if subtitle was available in my record sources.
In the cases of large collections of "ale verk" or "geklibene verk", subtitle would be very useful in indicating which specific works are included in each volume.

Best regards,
Assaf
